### ISSUE TITLE
Not reporting on arrays

### ISSUE THREAD

**Issue by oferg2** [junecastillote/Get-MXReport#1]
There is a bug in this version 1.0 which does not report on multiple mx records if found.
Line 181 (object initialize) should be inserted into the 'foreach' loop both in 'if' and 'else' statements blocks.

**Comment by junecastillote** [comment]
> There is a bug in this version 1.0 which does not report on multiple mx records if found.
> Line 181 (object initialize) should be inserted into the 'foreach' loop both in 'if' and 'else' statements blocks.

Thanks for catching this. Can you cite an example of a domain with multiple MX records - so I can also test and adjust?

**Comment by oferg2** [comment]
Google.com has multiple MX records for instance.
I am trying to custom this script to report on list of domains that their MX records are not as an array of accepted domains.

**Comment by junecastillote** [comment]
version 1.1 has been uploaded, which corrected the issue reported.
